# Generated by Django 3.2.1 on 2021-05-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('dept', models.CharField(blank=True, max_length=6, null=True)),
                ('creat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
